### ISSUE TITLE
"See all snapshot X appears in" should exclude old `nightly`s by default

### ISSUE THREAD

**Issue by andreasabel** [commercialhaskell/stackage-content#100]
E.g. https://www.stackage.org/package/Cabal/snapshots times out for me, likely because there are too many snapshots `Cabal` appears in, so the page construction takes too long.

But really, I am usually interested in _all __LTS__ snapshots X appears in_.  (And even for LTSs, I am only interested in the latest LTS for each GHC version.)

Maybe restricting the query to the LTSs and the latest nightly should be the default, and one could try to _really list all snapshots_ in a second step.

(Not sure I reported this issue in the correct project, is this the bug tracker for the website stackage.org?)

**Comment by ketzacoatl** [comment]
> (Not sure I reported this issue in the correct project, is this the bug tracker for the website stackage.org?)

@andreasabel, the haskell code and queries for dynamic aspects of stackage.org are in the `stackage-server` repo, which is at https://github.com/fpco/stackage-server/issues.

**Comment by andreasabel** [comment]
Moved to https://github.com/fpco/stackage-server/issues/311.
