### ISSUE TITLE
Compare Stackage snapshots on stackage.org is sometimes wrong

### ISSUE THREAD

**Issue by alaendle** [commercialhaskell/stackage-content#132]
E.g. https://www.stackage.org/diff/nightly-2023-01-24/nightly-2023-01-25
![grafik](https://user-images.githubusercontent.com/969523/214495279-1e6e3030-3b4a-4664-8125-30913f7adff4.png)
The real diff is:
```
commenter diff-snapshot nightly/2023/1/24.yaml nightly/2023/1/25.yaml 
^ core-data-0.3.8.0 -> 0.3.9.0
^ core-program-0.6.1.1 -> 0.6.2.1
^ digest-0.0.1.4 -> 0.0.1.5
^ pandoc-plot-1.6.0 -> 1.6.1
^ shelly-1.10.0 -> 1.10.0.1
^ type-level-kv-list-2.0.0 -> 2.0.1.1
```
I know that this repo doesn't contain the code to generate the diff - but it mentions stackage.org in the description and I haven't found a better place for this issue 😉

**Comment by mpilgrem** [comment]
@alaendle, the URL is now showing what you would expect. It looks to me from your screenshot like, for a period, `nightly-2023-01-25` did not know the libraries that ship with GHC. The relevant repository may be https://github.com/commercialhaskell/curator/.

**Comment by juhp** [comment]
I think this is the same issue as commercialhaskell/stackage#5352.
But yes fpco/stackage-server is actually the correct project I believe.

**Comment by alaendle** [comment]
Closing this as fpco/stackage-server#315 and commercialhaskell/stackage#5352 exist as a duplicate.
