### ISSUE TITLE
Doc should mention DNS pollution in China

### ISSUE THREAD

**Issue by HaskellZhangSong** [commercialhaskell/stackage-content#149]
I am sorry to mention this as a Chinese citizen. 

The DNS is badly polluted in China, so `githubusercontent.com` and other associated sites are not accessible in China.  Users can change `C:\Windows\System32\driver\etc\hosts` or linux hosts file to fix this
```
199.232.68.133 raw.githubusercontent.com
```

Or one may add the following to the host file

```
# GitHub
140.82.113.4 github.com 
140.82.114.4 gist.github.com
185.199.108.133 camo.githubusercontent.com
185.199.109.133 camo.githubusercontent.com
185.199.110.133 camo.githubusercontent.com
185.199.111.133 camo.githubusercontent.com
185.199.108.133 raw.githubusercontent.com
185.199.109.133 raw.githubusercontent.com
185.199.110.133 raw.githubusercontent.com
185.199.111.133 raw.githubusercontent.com
185.199.108.133 gist.githubusercontent.com
185.199.109.133 gist.githubusercontent.com
185.199.110.133 gist.githubusercontent.com
185.199.111.133 gist.githubusercontent.com
185.199.108.133 cloud.githubusercontent.com
185.199.109.133 cloud.githubusercontent.com
185.199.110.133 cloud.githubusercontent.com
185.199.111.133 cloud.githubusercontent.com
185.199.108.153 assets-cdn.github.com
185.199.109.153 assets-cdn.github.com
185.199.110.153 assets-cdn.github.com
185.199.111.153 assets-cdn.github.com
```

or set a more reliable DNS for the network setting. 

I am glad if this can be mentioned in the stack website doc.

**Comment by mpilgrem** [comment]
@HaskellZhangSong, matters related to the Stack tool should be raised in the Stack repository (https://github.com/commercialhaskell/stack/issues).

Access to GitHub from China seems to me to be a matter that is not specific to Stack. I am not convinced that Stack's online documentation website is the best place for advice.

That said, Stack's online documentation does have some existing advice for users in China: https://docs.haskellstack.org/en/stable/install_and_upgrade/#china-based-users. If that advice is to be extended, it should be done in a way that a beginner can follow.
