### ISSUE TITLE
stack ghc-9.10.1 hints missing os-string

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/stackage-content#215]
This confused stackage curator builds using ghc-9.10.1 perhaps, though only seemingly if os-string was listed in our build-constraints.

(Note there will also be new fileio in 9.12.1 for example.)

**Comment by mpilgrem** [comment]
I think this was missed because GHC 9.10.1 does not document `os-string` as a boot package: https://downloads.haskell.org/~ghc/9.10.1/docs/users_guide/9.10.1-notes.html#included-libraries.

**Comment by mpilgrem** [comment]
@juhp, I am not certain, but you may have to delete the incomplete `global-hints-cache.yaml` in the `pantry` directory of the Stack root to enjoy the corrected version.

**Comment by juhp** [comment]
Thank you!

I see that os-string now "appeared" in nightly-2024-12-12 (without me doing anything at least):

https://www.stackage.org/diff/nightly-2024-12-11/nightly-2024-12-12

**Comment by juhp** [comment]
(Interestingly I could not find any `global-hints-cache.yaml` file on our stackage build server.)
