### ISSUE TITLE
OpenBSD bindist GHC 8.2.1. for OpenBSD 6.0 doesn't really work?

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/stackage-content#28]
See https://ghc.haskell.org/trac/ghc/ticket/14044#ticket and https://github.com/fpco/stackage-content/issues/27#issuecomment-320323228.

**Comment by Blaisorblade** [comment]
Update: I've rechecked the links, no new comments.

**Comment by borsboom** [comment]
Given the upstream GHC issue is still open, and they didn't release any OpenBSD bindists for GHC 8.2.2, maybe we should consider GHC support for OpenBSD defunct for now and remove the non-working bindists from stack-setup-2.yaml.

@Blaisorblade @romanzolotarev Any thoughts?

**Comment by Blaisorblade** [comment]
@borsboom’s plan is fine with me.

On my side, I apologize for not following up on this. In practice, I volunteered some coordination effort (basically pinging others to figure out we’d need a bindist per major OpenBSD release), but because I don’t personally use OpenBSD, other tasks this got sidetracked.

What GHC and Stack might need is some volunteer who takes charge of the whole process including the builds (which volunteers did earlier) and/or automating them via virtual machines (which takes a n nontrivial setup cost).

But either the userbase is too small or users resort to alternatives. @romanzolotarev ideas?

I’m still attached to Stack support for multiple GHCs installed externally as an alternative for custom scenarios, but I’m afraid I won’t have time for that myself...

**Comment by jturner** [comment]
On a related note, GHC 8.6.4 is now part of OpenBSD 6.6 and I have a working stack with cabal install stack, but am getting the following: Unable to find installation URLs for OS key: openbsd64-maj6-min6

What are the steps to get a working bindist for stack?

**Comment by jturner** [comment]
> On a related note, GHC 8.6.4 is now part of OpenBSD 6.6 and I have a working stack with cabal install stack, but am getting the following: Unable to find installation URLs for OS key: openbsd64-maj6-min6
> 
> What are the steps to get a working bindist for stack?

Shouldn't --system-ghc remove the need for a bindist?
