### ISSUE TITLE
ghc-ncurses6-8.4.4 references libtinfo

### ISSUE THREAD

**Issue by MarianJancar** [commercialhaskell/stackage-content#52]
stack setup on a system with ncurses and without libtinfo downloads ghc-8.4.4-x86_64-fedora27-linux.tar.xz as ghc-ncurses6-8.4.4 , but as a binary in the tarbal references libtinfo, the setup fails.

Installing libtinfo on the system fixes the situation, but when libtinfo is available, stack setup downloads the same ghc-8.4.4-x86_64-fedora27-linux.tar.xz as ghc-tinfo6-8.4.4 this time, so I guess the ghc-ncurses6-8.4.4 is intented to be installed on libtinfo-less systems and referencing libtinfo is a bug in that case.

this is the output of the failing setup:
Writing implicit global project config file to: /home/marian/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Using latest snapshot resolver: lts-12.21
Downloaded lts-12.21 build plan.    
Preparing to install GHC (ncurses6) to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-ncurses6-8.4.4.                                      
Installing GHC ...                                                                       
Received ExitFailure 2 when running
Raw command: /usr/bin/gmake install
Run from: /home/marian/.stack/programs/x86_64-linux/ghc-ncurses6-8.4.4.temp/ghc-8.4.4/

**Comment by borsboom** [comment]
Thanks for your thorough debugging.  You're right, it shouldn't try to install the fedora27 (libtinfo linked) bindist on systems that only have libncurses6.  The distro transition to libtinfo/libncurses6 was messy for a while, and stack's approach to choosing a bindist wasn't quite right, and looks like things got a bit confused.

Now, the majority of distros include libtinfo6 (which may just be a symlink to libncurses6), and libtinfo6 is what the official GHC bindists are linked to.  Stack is also better at choosing the right bindist now.

At this point, I think we could remove the `ncurses6` entries from [stack-setup-2.yaml](https://github.com/commercialhaskell/stackage-content/blob/master/stack/stack-setup-2.yaml).  This means that in your situation you'd have gotten an error message saying that there's no `ncurses6` bindist available, which is much more sensible.

It might also be good to make this error message a bit more friendly for this situation and have it point the user to a FAQ entry.

**Comment by borsboom** [comment]
(I've now removed the `fedora27` bindists from the `ncurses6` variant entries)

**Comment by MarianJancar** [comment]
On 12/3/18 10:51 PM, Emanuel Borsboom wrote:
> Thanks for your thorough debugging. You're right, it shouldn't try to
> install the fedora27 (libtinfo linked) bindist on systems that only have
> libncurses6. The distro transition to libtinfo/libncurses6 was messy for
> a while, and stack's approach to choosing a bindist wasn't quite right,
> and looks like things got a bit confused.

Yes, I think so too.
Mine system is Gentoo, which only builds libtinfo when explicitly requested.

**Comment by MarianJancar** [comment]
On 12/3/18 10:59 PM, Emanuel Borsboom wrote:
> (I've now removed the |fedora27| bindists from the |ncurses6| variant
> entries)

It works now, thank you.
