### ISSUE TITLE
Add GHC bindist for linux-armv7-tinfo6

### ISSUE THREAD

**Issue by CaptJakk** [commercialhaskell/stackage-content#70]
I'm a tad out of my depth here so let me know if this is an insane ask. But we are currently trying to build a project with stack on a raspberry pi 4 and I'm getting an error message:

`Unable to find installation URLs for OS key: linux-armv7-tinfo6`

I saw that there is precedent for issues to this repository for bindists of ghc for nonstandard toolchains.

**Comment by borsboom** [comment]
The main place where we're discussion ARM support is here: https://github.com/commercialhaskell/stack/issues/2103
