### ISSUE TITLE
Wrong address in stack for the msys2-20200517-i686.tar.xz package

### ISSUE THREAD

**Issue by Syssiphus** [commercialhaskell/stackage-content#80]
The stack tool requests the path:
`/commercialhaskell/stackage-content/releases/download/msys2-20200517/msys2-20200517-i686.tar.xz`

while the correct path from the website seems to be:
`/commercialhaskell/stackage-content/releases/download/20200517/msys2-20200517-i686.tar.xz`

**Comment by snoyberg** [comment]
Can you send a PR to update it?
