### ISSUE TITLE
No setup information found for ghc-7.8.3 on your platform

### ISSUE THREAD

**Issue by H1h8** [commercialhaskell/stackage-content#88]
Hello all.
My platform is:
```
C>ver
Microsoft Windows [Version 10.0.19042.985]

C>stack   upgrade
Current Stack version: 2.7.1, available download version: 2.7.1
Skipping binary upgrade, you are already running the most recent version
```

Now, I did `stack new hello-world` and selected from https://www.stackage.org the oldest known resolver `lts-0.7` for the project just for some research purposes. But then the following happened:
```
C>stack build
No setup information found for ghc-7.8.3 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'windows64'.
Supported versions: ghc-7.8.4, ghc-7.10.1, ghc-7.10.2, ..., ghc-9.0.1
```
I do not understand what this means or what I can do to overcome it. Only found some similar issues reported, including on this list.

Then I switched to the second oldest resolver `lts-2.22`. But this was  not any good, either, and it produced:
```
C>stack  build
Stack no longer supports Cabal versions below 1.19.2,
but version 1.18.1.5 was found.
This invocation will most likely fail.
To fix this, either use an older version of Stack or a newer resolver
Acceptable resolvers: lts-3.0/nightly-2015-05-05 or later
...
```
Ok, next try is with `lts-3.22`. Now it actually WORKS. Other LTS snapshots were not checked.
But shouldn't they all "work"? -Kind of smoothly?

Now, this is my **real problem**:
I want to research several legacy Haskell projects on Github, some of which were abandoned 5 or 7 years ago. The original authors left no documentation, which versions of Cabal or Ghc were used to build the projects. So I do need very early snapshots.
Any helpful ideas would be greatly welcome.
Thanks.
Hubert

**Comment by qrilka** [comment]
@H1h8 I think the root of the problem here is the introduction of Stack 2 which had some breaking changes. Unfortunately I couldn't find blog post describing concrete details but the idea is that you should try the last release of Stack-1 (which should be 1.9.3) if you want to use such old LTS versions.

**Comment by juhp** [comment]
From the 2.1.1 release notes (changelog):

> No longer supports Cabal versions older than 1.19.2. This means projects using snapshots earlier than lts-3.0 or nightly-2015-05-05 will no longer build.

**Comment by H1h8** [comment]
@juhp and @qrilka, thanks for your cumulative explanation.
Good advice - read the changelog.
:-)
Indeed, I was not aware that there was a breaking change of behavior, although I did read the entire user guide.
Maybe v1.9.3 will help me.
