### ISSUE TITLE
Provide bindists for GHC 9.2

### ISSUE THREAD

**Issue by bergmark** [commercialhaskell/stackage-content#95]
I'd like to start tracking the stackage nightly upgrade to GHC 9.2 like we did for 9.0.1 in https://github.com/commercialhaskell/stackage/pull/6047. I think i need the bindists in stack-setup-2.yaml for that.

**Comment by bergmark** [comment]
I filed https://github.com/commercialhaskell/stackage-content/pull/96 for macosx, as that's what I personally need.

**Comment by borsboom** [comment]
I've now added all the standard bindists, as well as the linux-musl ones.

Note that I was not able to update the global hints, since the format of the release notes that the update-global-hints.hs script uses has changed.  So I'll leave this issue open until that part is complete as well.

**Comment by mpilgrem** [comment]
I am closing this issue, as I see that the global hints for GHC 9.2.2, 9.2.3 and 9.2.4 were added.
